trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACR_ServiceConnection_1'
    repository: 'nodejsimage'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
- task: HelmDeploy@1
  inputs:
    azureSubscriptionForACR: 'spconnection'
    azureResourceGroupForACR: 'rgterra'
    azureContainerRegistry: 'kubeacr1.azurecr.io'
    command: 'package'
    chartPath: 'helmado1'
    chartNameForACR: 'myapp-chart'
    chartPathForACR: 'helmado1'